spring.application.name=empty-web

spring.datasource.url=jdbc:postgresql://localhost:5432/erp
spring.datasource.username=erp
spring.datasource.password=erp

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect